<?php
declare(strict_types=1);

/**
 * Seed 006 — Vrais avis Airbnb + Booking (84 avis)
 * Exécuter : cd ~/villaplaisance-v6 && php seeds/006_seed_reviews.php
 */

require_once __DIR__ . '/../config.php';

$pdo = Database::getInstance();

// Vider la table
$pdo->exec("DELETE FROM vp_reviews");
echo "vp_reviews vidée.\n";

$reviews = [
    // ===== AIRBNB — VILLA (juillet/août) =====
    ['platform'=>'airbnb','offer'=>'villa','author'=>'Marianne','origin'=>'Waterloo, Belgique','rating'=>5,'review_date'=>'août 2025','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Nous avons passe un merveilleux sejour en famille a la Villa Plaisance. On s y sent comme chez soi. Tout nous a plu : le charme de la maison, la magnifique piscine, les activites et les visites dans la region. La maison est situee au calme mais proche des commerces et de jolies villes et villages du Vaucluse. Nous reviendrons surement ! Un grand merci a Alexandre et Jorge pour leur accueil, tout etait parfait"],
    ['platform'=>'airbnb','offer'=>'villa','author'=>'Jan','origin'=>'Anvers, Belgique','rating'=>4,'review_date'=>'juillet 2025','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"Nous avons passé un bon séjour dans cette maison de vacances bien située. Les hôtes ont été très accueillants et disponibles tout au long de notre séjour, ce que nous avons beaucoup apprécié. La piscine, grande et bien entretenue, est sécurisée par une clôture, ce qui est rassurant avec de jeunes enfants. La cuisine est bien équipée et les chambres ont pu être adaptées sans problème pour installer un lit bébé. La climatisation à l'étage était également un plus. Merci aux propriétaires pour leur accueil et leur écoute."],
    ['platform'=>'airbnb','offer'=>'villa','author'=>'Dirk','origin'=>'','rating'=>5,'review_date'=>'juillet 2025','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"Nous avons été chaleureusement accueillis, très gentils et serviables. Tout a été rendu possible. Les barrières linguistiques ont pu être surmontées, tout le monde était toujours serviable et disponible. Une belle propriété avec une grande piscine. Nous nous sommes sentis vraiment à l'aise. Jorge a préparé un merveilleux petit déjeuner, avec tout ce qui est frais et fait maison et était toujours là pour nous. Merci encore pour tout."],
    ['platform'=>'airbnb','offer'=>'villa','author'=>'Rachel','origin'=>'','rating'=>5,'review_date'=>'août 2023','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Un chez-soi loin de chez soi. Maison très bien équipée, merveilleuse piscine et à proximité des attractions. Alexandre a été très accueillant et serviable. Ma famille a passé un agréable séjour relaxant"],
    ['platform'=>'airbnb','offer'=>'villa','author'=>'Emma','origin'=>'Puteaux, France','rating'=>5,'review_date'=>'août 2022','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"Nous avons passé un super séjour entre amis dans la belle maison d'Alexandre. Il a été très accueillant et disponible. Maison très bien équipée. Cadre et piscine très agréable et calme. Nous recommandons !"],
    ['platform'=>'airbnb','offer'=>'villa','author'=>'Déborah','origin'=>'','rating'=>5,'review_date'=>'août 2022','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"Maison spacieuse idéale pour des vacances en famille ou entre amis. Un vrai cocon avec vue sur les vignes. Une immense piscine et une grande bibliothèque ferons le bonheur des petits et grands. Un très bon accueil."],
    ['platform'=>'airbnb','offer'=>'villa','author'=>'Carina','origin'=>'Le Coteau, France','rating'=>5,'review_date'=>'août 2022','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Nous avons passé une semaine formidable à la villa Plaisance avec sa grande piscine et son beau jardin. La maison est très bien équipée, surtout la cuisine. Nous étions huit personnes et nous n'avons jamais manqué de vaisselle ou d'ustensiles. La plus grande partie de notre séjour nous l'avons passé dehors, dans la piscine ou sur la terrasse. Nous n'oublierons jamais les soirées douces au bord de la piscine. Le chant des cigales et la silhouette des cyprès se détachant du ciel rendaient ce lieu enchanteur."],
    ['platform'=>'airbnb','offer'=>'villa','author'=>'Yashi','origin'=>'Cambridge, Royaume-Uni','rating'=>5,'review_date'=>'juillet 2022','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"Nous avons passé un super séjour à la Villa, l'emplacement est magnifique dans les vignobles. Alexandre et Jorge ont été très bons dans la communication et disponibles facilement à un SMS pour tout ce dont nous avions besoin. La piscine a été bien rangée et propre pour notre usage. La maison est belle avec beaucoup de caractère et bien équipée avec tout le nécessaire. Nous avons passé de très belles vacances"],
    ['platform'=>'airbnb','offer'=>'villa','author'=>'Charlotte','origin'=>'Allemagne','rating'=>5,'review_date'=>'juillet 2022','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"PERFECT ! Nous sommes arrivés dans la belle villa d'Alexandre et nous nous sommes immédiatement sentis comme à la maison ! Nous avions tout ce dont nous avions besoin : 2 chambres confortables, salle de bains, climatisation, espace, intimité et une belle piscine ! Jorge nous a gâtés avec le plus délicieux petit déjeuner (jus maison, confitures, brioche !) que nous attendions avec impatience chaque matin ! Il a été très attentionné et nous a donné les meilleurs conseils sur les visites et les restaurants de la région. Nous aimerions revenir un jour. On a adoré !!! Merci :)"],
    ['platform'=>'airbnb','offer'=>'villa','author'=>'Grace','origin'=>'Luxembourg','rating'=>5,'review_date'=>'juillet 2022','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"La maison est magnifique et l'espace était parfait pour nous, une famille de 4 personnes. La piscine est géniale. Jorge est un hôte et une personne extraordinaire, sincère, amicale et serviable ! Il nous a donné d'excellents conseils pour les vignobles et les restaurants. Il a fait un excellent petit-déjeuner à tartiner tous les matins avec du jus fraîchement préparé, de la salade de fruits, des brioches et des gaufres maison. Nous resterons certainement ici la prochaine fois !"],
    ['platform'=>'airbnb','offer'=>'villa','author'=>'Elisabeth','origin'=>'Göteborg, Suède','rating'=>5,'review_date'=>'juillet 2022','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Hôte très sympathique qui vit à proximité et fait en sorte que tout se passe au mieux. Toujours serviable avec des conseils et un accueil très chaleureux à la française !"],
    ['platform'=>'airbnb','offer'=>'villa','author'=>'Jarid','origin'=>'Seaford, Australie','rating'=>5,'review_date'=>'août 2022','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Séjour incroyable, hôtes incroyables. L'une de nos meilleures expériences Airbnb. J'ai hâte d'y séjourner à nouveau !"],

    // ===== AIRBNB — CHAMBRES D'HÔTES =====
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Mathieu','origin'=>'Riols, France','rating'=>5,'review_date'=>'octobre 2025','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Merci à Jorge pour ces 2 jours, Hote disponible, accueillant, et de bon conseil. Un petit dej incroyable. Attentionné envers les enfants comme avec les adultes. Chambres propres, conformes à la description. Merci, nous n'hésiterons pas lors d'un prochain séjour"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>"L'Arpenaz",'origin'=>'Magland, France','rating'=>5,'review_date'=>'octobre 2025','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Encore un grand merci pour cette accueil gorge excellent petits déjeuners au plaisir de revenir avec grand plaisir bien amicalement. Isabelle pascal et Aloha"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Tino','origin'=>'Alsdorf, Allemagne','rating'=>5,'review_date'=>'octobre 2025','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"j'ai séjourné avec mon chien une nuit. Jorge est tout simplement un gars formidable. super serviable et accommodant. Nous reviendrons avec plaisir."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'유진','origin'=>'Corée du Sud','rating'=>5,'review_date'=>'octobre 2025','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"C'était ma deuxième visite. Tout comme lorsque je suis venu il y a 3 ans, Jorge était toujours aussi gentil. Le logement était bien rangé, et mes amis étaient très satisfaits, donc je me suis senti bien !!!"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Rosemarie','origin'=>'Northampton, Royaume-Uni','rating'=>5,'review_date'=>'septembre 2025','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Jorge a été un hôte exceptionnel, nous avons séjourné 6 nuits et le petit déjeuner était différent chaque jour - et incroyable ! Il nous a également recommandé des endroits à visiter localement et nous a réservé des dégustations de vins à Châteauneuf-du-Pape. Les chambres étaient propres, confortables, parking sécurisé et belle piscine. À 10 minutes à pied de la gare - puis à 10 minutes en train d'Avignon. Merci beaucoup Jorge pour votre gentillesse, votre enthousiasme et votre hospitalité."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Gregory','origin'=>'Burtonsville, Maryland','rating'=>5,'review_date'=>'juin 2025','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Excellent endroit et Jorge a été un excellent hôte. Le petit déjeuner était également merveilleux. La seule chose à noter est qu'il s'agit d'une chambre dans la villa, pas de l'ensemble du logement."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Pierre','origin'=>'Port Townsend, Washington','rating'=>5,'review_date'=>'juin 2025','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"Une hospitalité exceptionnelle de la part de Jorge ! La piscine était charmante, propre et privée. Lits confortables, toilettes et douche. Au centre des principaux quartiers viticoles."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Manon','origin'=>'Annecy, France','rating'=>5,'review_date'=>'mai 2025','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Nous avons passé un excellent séjour à la Villa Plaisance ! Merci Jorge pour vos bons conseils pour les visites et les restaurants, et pour les petits-déjeuners incroyables tous les matins, qui étaient aussi copieux et faits-maison ! Tout etait conforme à la description par ailleurs, propreté irréprochable, et le jardin est très agréable pour se détendre."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Valentine','origin'=>'Paris, France','rating'=>5,'review_date'=>'mai 2025','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Goerges est un hôtes adorable et à l écoute. tout parfait."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'薇','origin'=>'Chine','rating'=>5,'review_date'=>'avril 2025','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Séjour très agréable. Maison calme et belle, chambre propre et bien rangée, hôte chaleureux et joyeux, nous nous sommes sentis comme chez nous. Surtout le petit déjeuner que l'hôte nous a préparé, c'était incroyable et nous ne voulions pas partir."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Jaime','origin'=>'Londres, Royaume-Uni','rating'=>5,'review_date'=>'janvier 2025','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"Le logement de Jorge et Alexander est idéalement situé pour visiter les vignobles à proximité. La chambre était chaude en hiver et j'ai passé une très bonne nuit de sommeil ! Encore mieux, le petit déjeuner ! Merci pour ce merveilleux séjour dans votre maison – je reviendrai pour l'été !"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Timo','origin'=>'Vantaa, Finlande','rating'=>5,'review_date'=>'octobre 2024','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Tout s'est très bien passé. L'accueil était chaleureux et le service excellent. Le petit déjeuner était meilleur que dans n'importe quel hôtel ! Nous avons bien dormi dans une chambre calme. Je recommande vivement cet hébergement à tout le monde."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Sylvie','origin'=>'','rating'=>5,'review_date'=>'octobre 2024','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Nous avons apprécié l'hospitalité de Jorge et son accueil. C'est une personne très serviable et prévenante. Nous avons eu le privilège de déguster et savourer ses produits maison lors de très bons petits déjeuners."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Nicolas','origin'=>'Olivella, Espagne','rating'=>5,'review_date'=>'octobre 2024','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Merci Jorge pour l'accueil et vos super petits dej !"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Louise','origin'=>'Waremme, Belgique','rating'=>5,'review_date'=>'septembre 2024','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Jorge nous a accueilli très chaleureusement, hôte réactif et flexible. Petits déjeuners excellent, le tout fait maison! Une villa calme et paisible, qui nous a réellement apporter le repos nécessaire. Nous nous réjouissons déjà d'y retourner !"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Jean-Michel','origin'=>'','rating'=>5,'review_date'=>'septembre 2024','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Accueil chaleureux. Excellents petits déjeûners maison."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Marie-Louise','origin'=>'','rating'=>5,'review_date'=>'août 2024','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Tout s'est très bien passé. Accueil et contact très bons."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Massimo','origin'=>'Rimini, Italie','rating'=>5,'review_date'=>'août 2024','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Nous n'aurions jamais imaginé trouver un endroit comme celui-ci. Une merveilleuse villa entourée de verdure, joliment décorée, avec une belle piscine, un excellent emplacement pour visiter la Provence. Chambre spacieuse, lumineuse et propre. Mais ce qui a fait de notre séjour un conte de fées, c'est Jorge. Ce n'était pas un simple hôte mais une personne spéciale et rare. Ses petits déjeuners sont excellents et toujours différents, il vous fait sentir à la maison. Nous ne nous souviendrons pas de lui seulement pour ses petits déjeuners mais pour la merveilleuse âme que nous avons eu la chance de rencontrer. Merci à Jorge pour tout. Arianna et Massimo"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Yu','origin'=>'Shanghaï, Chine','rating'=>5,'review_date'=>'juillet 2024','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Nous avons passé un séjour merveilleux à la villa. Jorge est un excellent majordome. Il est venu nous chercher à la gare et nous a préparé un très bon petit déjeuner. Situé dans une ville tranquille, facile à explorer comme Avignon, etc. Nous reviendrons certainement. Merci pour tout !"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Mélanie','origin'=>'Clermont-Ferrand, France','rating'=>5,'review_date'=>'juin 2024','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"Notre séjour de dernière minute a parfaitement démarré grâce à l'accueil chaleureux de Jorge, il soigne ses hôtes à merveille !! Bienveillant et arrangeant il nous a reçu dans un cadre idyllique pour se reposer, nous reviendrons avec grand plaisir pour quelques jours de plus. Nous recommandons vivement"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Lucas','origin'=>'France','rating'=>5,'review_date'=>'mai 2024','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Jorge a été très hospitalier et prévenant, il a tout mis en œuvre pour que notre séjour se déroule de la meilleure des manières et nous a proposé des programmes de visites sur mesure. Ses petits déjeuners 100% fait maison sont un vrai plus pour bien commencer la journée ! Nous reviendrons avec plaisir"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Rob','origin'=>'Sydney, Australie','rating'=>5,'review_date'=>'mai 2024','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"Nous avons passé un séjour incroyable à cet endroit. Jorge a été l'hôte idéal pour organiser des dégustations de vin pour nous et nous préparer un délicieux petit-déjeuner tous les jours. Hautement recommandé !"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'John','origin'=>'Menheniot, Royaume-Uni','rating'=>5,'review_date'=>'septembre 2023','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Nous voulions un point de départ pour explorer l'histoire romaine à Nîmes, Orange et Pont du Gard. Nous n'aurions pas pu choisir un meilleur endroit. La chambre était exactement comme annoncée, spacieuse et impeccablement propre. Les petits déjeuners préparés par Jorge étaient fantastiques. Jorge nous a donné d'excellentes adresses de restaurants, des conseils locaux et des informations sur certains sites romains. Nous avons hâte de revenir. John et Isabelle"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Andrea','origin'=>'Chorleywood, Royaume-Uni','rating'=>5,'review_date'=>'septembre 2023','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"bel emplacement, d'excellentes installations. Beaucoup d'espace dans le logement. Jorge a été un hôte de première classe et nous a aidés avec tout ce que nous avons demandé."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Carmen','origin'=>'Coazze, Italie','rating'=>5,'review_date'=>'juillet 2023','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"nous avons été accueillis et choyés et nous nous sommes sentis en famille. petit déjeuner super et avec des aliments authentiques. nous nous sommes détendus dans la piscine. nous avons été bien recommandés sur la façon de se déplacer dans les environs. très recommandé"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Bei','origin'=>'Paris, France','rating'=>5,'review_date'=>'juillet 2023','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Nous avons passé un séjour incroyable ici. Dès notre arrivée, l'hospitalité chaleureuse de Jorge nous a réconfortés. La maison était magnifique, avec une décoration de bon goût et une propreté impeccable. Belle piscine entourée d'un jardin verdoyant. Les connaissances de Jorge sur la région ont vraiment amélioré notre expérience. Le petit déjeuner maison de Jorge : fait maison, frais, sain, gourmand. Je recommande vivement ! Merci, Jorge, pour cette expérience inoubliable !"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Monica','origin'=>'Croydon, Australie','rating'=>5,'review_date'=>'juin 2023','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Par où commencer ? On a passé le meilleur moment chez Alexandre et Jorge. La maison était magnifique et la piscine très rafraîchissante ! Jorge a été le meilleur hôte Airbnb que nous ayons jamais eu ! Il a fait des petits déjeuners incroyables chaque matin et les a adaptés à nos préférences. Jorge a également eu la gentillesse de nous apprendre à faire de la brioche !"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Aurélie','origin'=>'Liège, Belgique','rating'=>5,'review_date'=>'juin 2023','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Une belle parenthèse à la Villa Plaisance ! « Comme à la maison » mais en mieux ! Jorge est hyper attentionné et de bons conseils pour les activités et restaurants aux alentours. Le cadre de la villa est magnifique et invite à la farniente. Les petits déjeuners faits maison sont délicieux. Merci pour ce moment de repos et ce bel accueil. Je recommande +++"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Wenfang','origin'=>'Taïwan','rating'=>5,'review_date'=>'juin 2023','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Jorge nous a gâtés avec un grand sourire chaleureux, une orientation détaillée de la villa et des environs. Il a non seulement recommandé un excellent restaurant à proximité, mais a également fait une réservation pour nous. Après ma promenade matinale sur la colline, Jorge nous a offert un petit déjeuner délicieux qu'il a préparé. Je veux revenir dès que possible pour un séjour beaucoup plus long."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Tobias','origin'=>'Hambourg, Allemagne','rating'=>4,'review_date'=>'juin 2023','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Nous avons passé un super séjour. Surtout l'hôte était très sympathique."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Matt','origin'=>'Charlotte, Caroline du Nord','rating'=>5,'review_date'=>'juin 2023','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Séjour incroyable, Jorge était incroyablement hospitalier. La piscine était parfaite, le trampoline était un ajout amusant, et le petit déjeuner était phénoménal. Une véritable expérience BNB, merci beaucoup Jorge et Sophie."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Mario','origin'=>'Québec City, Canada','rating'=>5,'review_date'=>'juin 2023','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"Un séjour extraordinaire ! M. Jorge est hôte des plus attentionnés. Ses précieux conseils sur nos visites dans la régions ainsi que ses délicieux déjeuners ont fait de notre passage chez lui un souvenir impérissable. Je recommande chaudement !"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Birgitta','origin'=>'Mannheim, Allemagne','rating'=>5,'review_date'=>'juin 2023','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"J'ai beaucoup aimé. Un petit bijou. Un hôte attentionné. De merveilleux conseils pour les activités. Petit déjeuner une petite œuvre d'art. Le séjour restera longtemps très positif dans nos souvenirs. Merci"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Annette','origin'=>'Bad Krozingen, Allemagne','rating'=>5,'review_date'=>'mai 2023','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Nous étions déjà 2x dans le logement et nous avons été très satisfaits comme la première fois. Jorge chouchoute ses clients et répond aux souhaits des clients si c'est possible pour lui. Le petit déjeuner est chaque jour à nouveau une merveilleuse surprise. Nous reviendrons."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Lisa','origin'=>'','rating'=>5,'review_date'=>'mai 2023','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Nous avons passé une nuit de passage. Tout était tel que décrit, il ne manquait de rien ! Le matin, il y avait un très bon petit déjeuner français !"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Catherine','origin'=>'Angleterre, Royaume-Uni','rating'=>5,'review_date'=>'mai 2023','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"Jorge a été une star absolue, il m'a aidé à trouver 150 roses blanches, tarpaulins, 10 énormes seaux pour le mariage de mes fils le lendemain, rien n'était trop compliqué, c'était un vrai super hôte"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Graham','origin'=>'Queensland, Australie','rating'=>5,'review_date'=>'mai 2023','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Nous avons été accueillis par Jorge pour notre séjour de 3 nuits et c'est vraiment un Superhost. Ses petits déjeuners sont excellents et il a fait tout son possible pour nous aider à trouver des restaurants, faire des réservations et suggérer des voyages à proximité. L'hébergement était très confortable dans un cadre paisible. Hautement recommandé, si vous visitez les zones viticoles à proximité."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Nicolas','origin'=>'Paris, France','rating'=>5,'review_date'=>'avril 2023','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"La Villa Plaisance est très facilement accessible et à proximité de tous les centres d'intérêt de la région. Jorge est très accueillant, nous a donné de bons conseils de visite, et nous à préparé des petits déjeuners succulents ! Je recommande !"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Elisabeth','origin'=>'Hamm, Allemagne','rating'=>5,'review_date'=>'avril 2023','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"La plus belle expérience Airbnb jamais. Jorge nous a accueillis chaleureusement et a partagé son domicile avec nous de manière simple, sympathique et généreuse. Il nous a gâtés le matin avec un merveilleux petit déjeuner : des variations sur des brioches maison, des bols de fruits frais, de délicieuses confitures, un yaourt fraîchement préparé, un jus d'orange fraîchement pressé. Et après cela, une balade à vélo à Châteauneuf-du-Pape. Super expérience."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Laurène','origin'=>'Marseille, France','rating'=>5,'review_date'=>'octobre 2022','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Nous avons passé un excellent séjour dans cette charmante maison au milieu des vignes. Nous avons été très chaleureusement accueillis par Jorge, qui est d'une extrême gentillesse et générosité. Il nous a conseillé sur notre week-end et a pris le temps de se renseigner pour nous, afin que nous visitions les domaines de la région. Mention spéciale à l'excellente brioche faite maison, ainsi qu'au reste du petit déjeuner maison. Jorge a été aux petits soins avec nous, ce qui nous donne très envie de revenir."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Valérie','origin'=>'Lyon, France','rating'=>5,'review_date'=>'octobre 2022','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"C'est mon troisième séjour dans cette maison d'hôte … toujours un plaisir … je recommande"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Angélique','origin'=>'Leidschendam, Pays-Bas','rating'=>5,'review_date'=>'octobre 2022','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Jorge sait mieux que quiconque comment recevoir ses voyageurs. La convivialité, l'excellent petit déjeuner, pour nous, ce furent deux jours inoubliables. Nous aimerions revenir ici."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Alexandra','origin'=>'Liège, Belgique','rating'=>5,'review_date'=>'septembre 2022','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Hôtes très sympathiques et attentionnés. Maison superbe et idéalement située pour visiter la région. Tout était parfait. Rendez-vous est pris pour l'année prochaine. MERCI POUR TOUT"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Josephine','origin'=>'Monterey, Californie','rating'=>5,'review_date'=>'septembre 2022','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"L'emplacement idéal pour visiter Châteauneuf-du-Pape. Les deux chambres étaient spacieuses et la vue de nos fenêtres était spectaculaire. Alexandre et George étaient des hôtes extraordinaires. Nous a accueillis avec Rosé réfrigéré, nous a aidés à sélectionner nos restaurants et nos visites de vignobles. Une promenade dans leur vignoble et une baignade dans leur piscine cristalline. George nous a servi un élégant petit déjeuner, du jus d'orange fraîchement pressé, des fruits et des pâtisseries fraîches."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Nate','origin'=>'San Francisco, Californie','rating'=>5,'review_date'=>'septembre 2022','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Super séjour. Belle piscine. Merci pour le petit déjeuner !"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Ellen','origin'=>'Maine, États-Unis','rating'=>5,'review_date'=>'juin 2022','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Merci Alexandre et Jorge pour cette expérience fantastique ! C'était notre AirBNB préféré du voyage ! C'était génial d'avoir la piscine par une chaude journée, les hôtes étaient extrêmement accueillants, et Jorge a pris grand soin de nous, notamment en nous faisant un petit-déjeuner génial - la meilleure salade de fruits que j'aie jamais mangée !"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Clemence','origin'=>'Plombières-lès-Dijon, France','rating'=>5,'review_date'=>'juin 2022','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"hôte très accueillant et très sympathique. Le logement est idéalement situé et très confortable. Je recommande"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Faustine','origin'=>'Paris, France','rating'=>5,'review_date'=>'juin 2022','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Notre séjour a été paradisiaque. Jorge et Alexandre ont été aux petits soins et absolument adorables. Un petit déjeuner indescriptible... tout est fait maison par Jorge, on a failli pleurer tellement c'était bon. Et bien sûr, la région est sublime. Les vins, les paysages, la piscine, les restaurants nous ont fait regretter amèrement d'être restées seulement 2 nuits. J'ai déjà recommandé cette adresse et j'ai hâte de revenir !"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Nadja','origin'=>'Géorgie, États-Unis','rating'=>5,'review_date'=>'juin 2022','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Cette villa est d'un excellent rapport qualité-prix avec de superbes hôtes. Nous avons largement dépassé nos attentes et nous reviendrons."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Christine','origin'=>'Saint-Genis-les-Ollières, France','rating'=>5,'review_date'=>'juin 2022','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"La maison de Jorge et d'Alexandre est très bien située entre Orange et Avignon, près du Ventoux et des dentelles de Montmirail. Lors de notre petit séjour, tout était parfait (les chambres, le petit déjeuner, la piscine, l'apéritif au bord de la piscine, la balade dans les vignes, l'accueil). Ce fut un vrai moment de plaisir."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Nancy','origin'=>'Austin, Texas','rating'=>5,'review_date'=>'juin 2022','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"Quelle expérience merveilleuse ! La villa et le terrain environnant étaient charmants et la piscine était très relaxante. C'est Jorge, cependant, qui a vraiment rendu notre séjour exceptionnel avec sa personnalité amicale et compétente et son incroyable petit déjeuner fait maison ! Merci encore et nous espérons revenir !"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Quentin','origin'=>'Attignat, France','rating'=>5,'review_date'=>'juin 2022','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Superbe séjour avec Jorge et Alexandre. Idéalement situé au milieu des vignes et non loin de Châteauneuf-du-Pape. Commencez votre journée avec un superbe petit déjeuner copieux et fait maison (brioche, confitures, jus d'orange, fruits de saison), piquez par la suite une tête dans l'immense piscine et enchaînez sur les bons conseils de l'hôte une visite des alentours. Je recommande pour un voyage en famille ou en couple pour le calme, la localisation, la maison (sublime maison art déco avec piscine) et l'accueil au top."],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Barney','origin'=>'New York, New York','rating'=>5,'review_date'=>'mai 2022','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Une propriété agréable avec un hôte charmant. Un bel endroit pour une famille avec un ou deux enfants. Et un excellent petit déjeuner avec des crêpes, une brioche maison parfaite et plus encore !"],
    ['platform'=>'airbnb','offer'=>'bb','author'=>'Jean-Noël','origin'=>'Montpellier, France','rating'=>5,'review_date'=>'mai 2022','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Une agréable nuit en famille à 20 minutes d'Avignon et 12 minutes du parc Spirou. Belle maison des années 20 entourée de vignes. Jorge nous a offert un accueil chaleureux, de bons conseils et un succulent petit déjeuner maison. Les chambres en enfilade sont idéales pour une famille de 4/5 personnes."],

    // ===== BOOKING =====
    ['platform'=>'booking','offer'=>'bb','author'=>'Alice','origin'=>'Allemagne','rating'=>5,'review_date'=>'février 2026','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Très simple mais propre et convivial"],
    ['platform'=>'booking','offer'=>'bb','author'=>'touria','origin'=>'France','rating'=>9,'review_date'=>'octobre 2025','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"Nous avons apprécié l'endroit, très agréable. M. Jorge était à notre écoute, disponible et surtout très discret. Le petit déjeuner est formidable et très frais. Je recommande énormément."],
    ['platform'=>'booking','offer'=>'bb','author'=>'Jeroen','origin'=>'Pays-Bas','rating'=>10,'review_date'=>'juin 2025','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"C'est le meilleur hébergement où nous ayons séjourné dans le sud de la France. Jorge est tellement sympathique et nous a tous accueillis avec gentillesse : nous avons des restrictions alimentaires et il a préparé comme par magie de délicieux petits déjeuners alternatifs (différents pendant deux jours) et a surpris notre enfant avec des biscuits. Les chambres sont impeccables, nous avons apprécié la piscine et la climatisation. Nous sommes allés dans les endroits recommandés par Jorge. Nous serions ravis de revenir !"],
    ['platform'=>'booking','offer'=>'bb','author'=>'FRED&MARINE','origin'=>'France','rating'=>10,'review_date'=>'juin 2025','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"L'hôte est aux petits soins. La maison est magnifique et la piscine incroyable. Le petit déjeuner du matin est tout simplement magique. Merci encore pour l'accueil : nous reviendrons sans hésiter et recommandons évidemment cette adresse !"],
    ['platform'=>'booking','offer'=>'bb','author'=>'Giorgos','origin'=>'Grèce','rating'=>10,'review_date'=>'juin 2025','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"La propriété était très propre et magnifiquement située à Bédarrides, à proximité de Châteauneuf-du-Pape. Notre hôte, Jorge, est une personne formidable, très sympathique, qui a toujours fait tout son possible pour nous faire plaisir. Le petit-déjeuner qu'il nous a préparé était incroyable !! Nous avons également adoré passer du temps à la piscine. Je recommande sans hésiter et je reviendrai très bientôt !"],
    ['platform'=>'booking','offer'=>'bb','author'=>'Maud','origin'=>'France','rating'=>9,'review_date'=>'mai 2025','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Accueil chaleureux, literie confortable et petit déjeuner complet (fait maison) et copieux !"],
    ['platform'=>'booking','offer'=>'bb','author'=>'Robert','origin'=>'France','rating'=>10,'review_date'=>'mai 2025','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"La proximité des lieux touristiques. La diligence et son amabilité de Jorge"],
    ['platform'=>'booking','offer'=>'bb','author'=>'christine','origin'=>'France','rating'=>9,'review_date'=>'mai 2025','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Qualité et gentillesse de l'accueil. De très bons produits au petit déjeuner. Jolie maison et très joli jardin. L'hôte vous partage ses bonnes adresses."],
    ['platform'=>'booking','offer'=>'bb','author'=>'Michael','origin'=>'Allemagne','rating'=>10,'review_date'=>'avril 2025','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"Jorge, l'hôte, nous a donné beaucoup de conseils et avait beaucoup de connaissances locales à partager sur les endroits que nous avons visités. Grande hospitalité ! Nous nous sommes sentis comme à la maison et avons passé de merveilleuses journées en Provence. Le petit déjeuner était magnifique ! Tous les produits faits maison ou bio au goût merveilleux."],
    ['platform'=>'booking','offer'=>'bb','author'=>'Lauren','origin'=>'France','rating'=>10,'review_date'=>'avril 2025','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Tout ! Nous avons passé un merveilleux séjour !"],
    ['platform'=>'booking','offer'=>'bb','author'=>'Elias','origin'=>'Pays-Bas','rating'=>10,'review_date'=>'avril 2025','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Tout a été bien pris en charge"],
    ['platform'=>'booking','offer'=>'bb','author'=>'Krystelle F','origin'=>'France','rating'=>10,'review_date'=>'mars 2025','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"L'accueil de Jorge et ses bons conseils. Un super petit déjeuner avec des produits frais et locaux. Très belle collection de livres à disposition pour passer une belle soirée lecture."],
    ['platform'=>'booking','offer'=>'bb','author'=>'Karim','origin'=>'Tunisie','rating'=>10,'review_date'=>'février 2025','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Authenticité des lieux et le petit dejeuner avec des ingredients locaux"],
    ['platform'=>'booking','offer'=>'bb','author'=>'Chrystelle','origin'=>'France','rating'=>10,'review_date'=>'février 2025','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"Accueil au top par Jorge. A préparé un excellent petit déjeuner."],
    ['platform'=>'booking','offer'=>'bb','author'=>'Katia','origin'=>'France','rating'=>9,'review_date'=>'janvier 2025','featured'=>1,'home_carousel'=>0,'status'=>'published',
     'content'=>"En déplacement professionnel, nous avions loué pour 1 nuit. L'accueil de Jorge fut extra, sympathique, discret mais disponible. Jolie maison conviviale. Heureuse surprise au petit-déjeuner: confitures, brioche et yaourts faits maison. Le concept authentique de la maison d'hôte. Nous y retournerons volontiers à l'occasion d'un autre séjour dans la région."],
    ['platform'=>'booking','offer'=>'bb','author'=>'Molto garcia','origin'=>'Espagne','rating'=>10,'review_date'=>'janvier 2025','featured'=>0,'home_carousel'=>0,'status'=>'published',
     'content'=>"En général, tout était parfait."],
    ['platform'=>'booking','offer'=>'bb','author'=>'Matthieu','origin'=>'France','rating'=>10,'review_date'=>'décembre 2024','featured'=>1,'home_carousel'=>1,'status'=>'published',
     'content'=>"Excellent accueil, on ne manque de rien, les chambres sont impeccablement tenues. Le petit déjeuner, copieux, est remarquable par sa qualité, avec de nombreux produits faits maison. Nous recommandons vivement!"],
];

$stmt = $pdo->prepare("
    INSERT INTO vp_reviews
        (platform, offer, author, origin, rating, review_date, content, featured, home_carousel, status)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
");

$count = 0;
foreach ($reviews as $r) {
    $stmt->execute([
        $r['platform'],
        $r['offer'],
        $r['author'],
        $r['origin'],
        $r['rating'],
        $r['review_date'],
        $r['content'],
        $r['featured'],
        $r['home_carousel'],
        $r['status'],
    ]);
    $count++;
}

echo "✅ {$count} avis insérés dans vp_reviews.\n";
echo "   • Airbnb villa   : 12\n";
echo "   • Airbnb BB      : 55\n";
echo "   • Booking BB     : 17\n";
